import { useState, useEffect } from 'react';
import type { DailyRecord, AnnualMetrics, ClimateSummary } from '../types/climate.ts';

const DATA_BASE_URL = `${import.meta.env.BASE_URL}data/`;

export interface ClimateDataState {
    dailyData: DailyRecord[] | null;
    metrics: Record<number, AnnualMetrics> | null;
    summary: ClimateSummary | null;
    loading: boolean;
    error: Error | null;
}

/**
 * Fetches all three climate data files in parallel.
 *
 * Data sources (generated by data/scripts/generate_web_data.py):
 *  • climate_data.json — 31,412 daily records (1940–2025)
 *  • metrics.json      — 86 annual ETCCDI metric records
 *  • summary.json      — headline stats
 *
 * Uses DATA_BASE_URL (= import.meta.env.BASE_URL + "data/") so paths work
 * in both local dev (/) and GitHub Pages (/pindamonhangaba-climate/).
 */
export function useClimateData(): ClimateDataState {
    const [state, setState] = useState<ClimateDataState>({
        dailyData: null,
        metrics: null,
        summary: null,
        loading: true,
        error: null,
    });

    useEffect(() => {
        let cancelled = false;

        async function fetchAll() {
            try {
                const [climateRes, metricsRes, summaryRes] = await Promise.all([
                    fetch(`${DATA_BASE_URL}climate_data.json`),
                    fetch(`${DATA_BASE_URL}metrics.json`),
                    fetch(`${DATA_BASE_URL}summary.json`),
                ]);

                if (!climateRes.ok)
                    throw new Error(`climate_data.json: HTTP ${climateRes.status}`);
                if (!metricsRes.ok)
                    throw new Error(`metrics.json: HTTP ${metricsRes.status}`);
                if (!summaryRes.ok)
                    throw new Error(`summary.json: HTTP ${summaryRes.status}`);

                const [climate, metricsRaw, summaryData] = await Promise.all([
                    climateRes.json() as Promise<DailyRecord[]>,
                    metricsRes.json() as Promise<Record<string, AnnualMetrics>>,
                    summaryRes.json() as Promise<ClimateSummary>,
                ]);

                // metrics.json uses string keys — convert to number keys
                const metrics: Record<number, AnnualMetrics> = {};
                for (const [yearStr, val] of Object.entries(metricsRaw)) {
                    const yearNum = parseInt(yearStr, 10);
                    metrics[yearNum] = {
                        ...val,
                        year: yearNum,
                    };
                }

                if (!cancelled) {
                    setState({
                        dailyData: climate,
                        metrics,
                        summary: summaryData,
                        loading: false,
                        error: null,
                    });
                }
            } catch (err) {
                if (!cancelled) {
                    setState(prev => ({
                        ...prev,
                        loading: false,
                        error: err instanceof Error ? err : new Error(String(err)),
                    }));
                }
            }
        }

        fetchAll();
        return () => {
            cancelled = true;
        };
    }, []);

    return state;
}
